[package]
name = "sfft-griffin"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
image = "0.24"
rustfft = "6.1"
hound = "3.5"
rand = "0.8"
num-complex = "0.4"
